Repository senzowayne/resavo, pull requests merged in 2020-10, with the labels that each got.

#74 Update migration
  src/Migrations/Version20191116163056.php
  src/Migrations/Version20200209113219.php
  src/Migrations/Version20201008161841.php
Labels: En cour de progression, hacktoberfest

#75 Fix + improve booking day
  config/packages/security.yaml
  src/Controller/BookingController.php
  templates/macro/_view_resa.html.twig
  templates/reservation/booking-day.html.twig
Labels: Amélioration, Renforcement, hacktoberfest

#76 BUMP symfony
  config/packages/doctrine_migrations.yaml
  src/Migrations/Version20200209113219.php
  src/Migrations/Version20201008161841.php
  symfony.lock
Labels: UPDATE, hacktoberfest

#73 Improve booking controller
  src/Controller/BookingController.php
Labels: Amélioration

#77 Add a booking + paypal manager
  src/Controller/BookingController.php
  src/Manager/AbstractManager.php
  src/Manager/BookingManager.php
  src/Manager/PaypalManager.php
  src/Service/Paypal/CaptureAuthorization.php
  src/Service/Paypal/GetOrder.php
Labels: Amélioration, hacktoberfest

#79 ISSUE-#78 : Fix datetepicker getMeeting
  assets/js/components/Meeting.vue
Labels: bug, hacktoberfest

#81 Add makefile
  Makefile
Labels: Nouvelle fonctionnalitée

#87 Clean controller
  src/Controller/AdminController.php
  src/Controller/AvailableBookingController.php
  src/Controller/MeetingController.php
  src/Controller/NotificationController.php
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/Manager/BookingManager.php
  src/Manager/UserManager.php
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
Labels: Amélioration

#89 Improve Makefile and docker-compose
  .env
  .gitignore
  Makefile
  README.md
  docker-compose.yaml
  docker/nginx/nginx.conf
  docker/node-alpine/Dockerfile
  docker/php-fpm/Dockerfile
  docker/php-fpm/php.ini
  docker/php-fpm/xdebug.ini
Labels: Renforcement

#80 Add event subscriber for booking name
  config/packages/admin/entities/booking.yaml
  config/services.yaml
  src/Controller/BookingController.php
  src/Events/ResolveBookingSubscriber.php
  src/Manager/PaypalManager.php
  templates/reservation/resume.html.twig
Labels: Amélioration, hacktoberfest

#90 Add php stan + fix all errors
  composer.json
  config/packages/prod/deprecations.yaml
  config/packages/security.yaml
  config/preload.php
  phpstan.neon
  src/Controller/AdminController.php
  src/Controller/AvailableBookingController.php
  src/Controller/BookingController.php
  src/Controller/CheckBookingController.php
  src/Controller/MeetingController.php
  src/Controller/NotificationController.php
  src/Controller/SecurityController.php
  src/Controller/StaticController.php
  src/Controller/UserController.php
  src/DataProvider/DateBlockedDateProvider.php
  src/DataProvider/MeetingDataProvider.php
  src/Doctrine/CurrentUserExtension.php
  src/Entity/Booking.php
  src/Entity/ConfigMerchant.php
  src/Entity/DateBlocked.php
  src/Entity/Meeting.php
  src/Entity/PasswordUpdate.php
  src/Entity/Paypal.php
  src/Entity/Role.php
  src/Entity/Room.php
  src/Entity/Salle.php
  src/Entity/Seance.php
  src/Entity/User.php
  src/Events/ResolveBookingSubscriber.php
  src/Form/BookingType.php
  src/Form/ConfigMerchantType.php
  src/Form/MeetingType.php
  src/Form/PasswordUpdateType.php
  src/Form/RoomType.php
  src/Form/UserType.php
  src/Kernel.php
  src/Manager/BookingManager.php
  src/Manager/PaypalManager.php
  src/Manager/UserManager.php
  src/Security/LoginFormAuthenticator.php
  src/Service/Paypal/CaptureAuthorization.php
  src/Service/Paypal/GetOrder.php
  symfony.lock
  tests/bootstrap.php
Labels: Amélioration

#91 Fix Packages depreciation + Update
  Makefile
  composer.json
  config/bundles.php
  config/packages/security.yaml
  config/packages/twig_extensions.yaml
  config/services.yaml
  src/Events/ResolveBookingSubscriber.php
  symfony.lock
  templates/reservation/resume.html.twig
  templates/user/historique.html.twig
Labels: UPDATE

#92 Use webpack namespace
  assets/js/app.js
  assets/js/components/Available.vue
  assets/js/components/DatePicker.vue
  assets/js/components/Meeting.vue
  assets/js/components/Notification.vue
  assets/js/components/Payment.vue
  assets/js/components/Room.vue
  assets/js/pages/reservation.vue
  assets/js/resavo.js
  webpack.config.js
Labels: Amélioration
